export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';


export const REQUEST_SEARCH_PENDING = 'REQUEST_SEARCH_PENDING';
export const REQUEST_SEARCH_SUCCESS = 'REQUEST_SEARCH_SUCCESS';
export const REQUEST_SEARCH_FAILED = 'REQUEST_SEARCH_FAILED';
